### ISSUE TITLE
latest release does not have correct version info

### ISSUE THREAD

**Issue by randallmeeker** [HalfTime/angular-gizmos#5]
latest releases download tagged as `2.6.1` downloads  `2.6.0`

**Comment by nddeluca** [comment]
ugh I didn't even notice.  Looks like a bug in the gulp script for release - it automatically bumps the version but looks like it commits the version bump after creating the git tag.  I'll release a new version with a corrected bower.json file.

**Comment by nddeluca** [comment]
fixed

**Comment by randallmeeker** [comment]
ya, it looks like all versions of late have been behind. I just noticed as I'm going through and testing earlier versions.

**Comment by nddeluca** [comment]
yeah I've been using `gulp tag and gulp tag --minor` for making new versions since 2.5.6 or so.  I did this last one manually now.
